### ISSUE TITLE
1.3.0 broken on server

### ISSUE THREAD

**Issue by jeremiahwinsley** [EccentricVamp/EccentricTome#13]
**Versions**
 - Minecraft: 1.18.2
 - Eccentric Tome: 1.3.0

**Describe the bug**
Mod attempts to load client classes on server and fails.

**To Reproduce**
`./gradlew runServer`

**Additional context**
https://gist.github.com/jeremiahwinsley/34cc8bab1fc77ef03a4c416bcb06eb52

**Comment by EccentricVamp** [comment]
Thanks for catching that! I didn't realize the server would attempt to handle RenderOverlay events, and I do all of my testing client-side.

Do you know of an quicker way to test mods? I run the client debugger after every patch to make sure it still runs, after every minor revision I test out the general features. But those are both getting pretty tedious. I did some quick googling but I couldn't find any testing frameworks currently being maintained for Minecraft Forge mods.

**Comment by EccentricVamp** [comment]
This is now patched in [Eccentric Tome 1.3.1](https://www.curseforge.com/minecraft/mc-mods/eccentric-tome/files/3749854)

**Comment by jeremiahwinsley** [comment]
Haven't tried it out yet (I still do my testing manually), but 1.18.2 has the Mojang Game Test Framework. Writeup by SizableShrimp here: https://gist.github.com/SizableShrimp/60ad4109e3d0a23107a546b3bc0d9752
