### ISSUE TITLE
Please allow access to your mods for third party lanuchers.

### ISSUE THREAD

**Issue by blackd** [EccentricVamp/EccentricTome#18]
With the new curseforge REST API rollout your mods are currently only accessible using the curseforge site and the curseforge app.

Could you please allow access for launchers like ATLauncher.
For more info https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle

Not all people use WIndows which makes impossible to use CurseForge on Linux so third party launchers are our only way to play

**Comment by EccentricVamp** [comment]
I didn't realize that CurseForge did something that dumb. I'm on Windows, but I don't use the CurseForge app either, mainly due to bloat and silly stuff like this.

I would like to keep track of how many downloads my mod has. Would it fix your issue if I reuploaded the mod to [Modrinth](https://modrinth.com/)? It looks like ATLauncher supports Modrinth.

**Comment by blackd** [comment]
I'm not sure about Modrinth how will the other launchers know how to find the mod there. Having different mod ID and so on. 

But when it comes to counting downloads my experience with my mod is that downloads from other launchers have never been part of the number on the courseforge site.

Well I did the that experiment when my mod wasn't that popular and I had handful of friends download it using atlauncher and then the site. Only the site counted after 4 hours.

Now I sow slite increase in downloads after the change but I can't be sure about the reason.

**Comment by EccentricVamp** [comment]
> I'm not sure about Modrinth how will the other launchers know how to find the mod there.

If you want to know how the Modrinth API works, you can read the [docs](https://docs.modrinth.com/docs/getting-started/). It's basically the same as CurseForge API.

> But when it comes to counting downloads my experience with my mod is that downloads from other launchers have never been part of the number on the courseforge site.

I didn't realize that, but all the more reason to move away from CurseForge.

Eccentric Tome has now been uploaded to Modrinth. https://modrinth.com/mod/eccentric-tome

**Comment by EccentricVamp** [comment]
Marking this as closed due to inactivity. Re-open it and leave a comment if your issue isn't fixed

**Comment by blackd** [comment]
sorry I mixed up the issues that's why I deleted the comment immediately

**Comment by EccentricVamp** [comment]
Ah, okay. No worries. Should I close this then?

**Comment by ExistingProgrammer** [comment]
> I would like to keep track of how many downloads my mod has. Would it fix your issue if I reuploaded the mod to [Modrinth](https://modrinth.com/)? It looks like ATLauncher supports Modrinth.

![image](https://user-images.githubusercontent.com/71560815/204181610-2956c8b5-5da3-45b1-9e60-5f44e1aab50b.png)

Still a QoL issue, as downloading curseforge packs from third-party launchers does not try to download the mods from modrinth, but thanks for uploading the mod to modrinth. (Screenshot of downloading Enigmatica 9 from PrismLauncher)

**Comment by EccentricVamp** [comment]
Keeping track of downloads doesn't matter to me as much as it used to. I've now enabled third party downloads on CurseForge
