### ISSUE TITLE
[1.18.2] Exiting the "Right-click" screen with "e"

### ISSUE THREAD

**Issue by INooBTooMuch** [EccentricVamp/EccentricTome#28]
**Describe the solution you'd like**
Other than using "escape" to exit the book selection screen, maybe using "e" would be easier.

**Describe alternatives you've considered**
In case this isn't possible maybe making a key-bind that is "escape" on default and you can change it to "e". 
Although I don't know how hard this would be or if t would interfere with any mods.

**Comment by EccentricVamp** [comment]
Sorry for the wait. This should be fixed in Eccentric Tome 1.9.0

I was able to bind it to the inventory key ("e" by default). Let me know it works for you

**Comment by INooBTooMuch** [comment]
Yes, its working all fine. I don't see any problems.
