### ISSUE TITLE
[1.18.2]EccentricTome only allowing a single tome

### ISSUE THREAD

**Issue by HalcyonSeas73** [EccentricVamp/EccentricTome#3]
EccentricTome version: 1.0
Patchouli version: 1.18.2-66
Forge version: 40.0.36
Minecraft version: 1.18.2

Combining a (filled) EccentricTome with another guidebook (in order to add it to the Tome) results in the previous guidebook being overwritten by the new one.

![Untitled1](https://user-images.githubusercontent.com/84727791/161404637-501ab65a-e0dd-4b19-919e-3b457ab0b7ad.png)

![Untitled2](https://user-images.githubusercontent.com/84727791/161404642-31e005fb-c140-4a0c-a478-5ff7df518836.png)

**Comment by EccentricVamp** [comment]
Might be specific to these guide books. I tested it with other ones (Tinker's Construct, XNet, and Extreme Reactors) and they seem to work. Thanks for submitting the issue. I'll investigate.

Note to self: maybe an issue with some of Vakii's Patchouli books not being registered under the correct mod

**Comment by EccentricVamp** [comment]
Confirmed. Poorly implemented Patchouli guide books get registered to the same resource location, so the Tome thinks they're the same item.

**Comment by EccentricVamp** [comment]
@HalcyonSeas73, I've fixed this issue and published v1.0.1 to CurseForge. I tested it with Mystical Agriculture and it worked. Which mod did the "Network Guide Book" come from?

**Comment by HalcyonSeas73** [comment]
Network Guide Book is from [Simple Storage Network](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network), by Lothrazar.
