### ISSUE TITLE
Unable to attach enchanted books

### ISSUE THREAD

**Issue by DumbXBoxAcct** [EccentricVamp/EccentricTome#30]
**Versions**
 - Minecraft: [e.g. 1.19.2]
 - Eccentric Tome: 1.19.2-1.9.0-beta
 - Forge 1.19.2-43.1.33

**Describe the bug**
With all Mods and Resource Packs removed, just running Forge 43.1.33, Minecraft 1.19.2 and Eccentric Tome 1.9.0, it crafts the Eccentric Tome with a book and a bookcase, but it will not let me craft an Eccentric Tome with an Enchanted Book.  Literally, nothing happens when I place both an Eccentric Tome and an Enchanted Book in the spaces of a Crafting Table shown in the description.

I have tried "whitelisting" "minecraft:enchanted_book" and "enchanted" in the .TOML file under "items" and "names," respectively, but combining an e-tome with an Enchanted book simply doesn't make anything happen.

Perhaps I'm not understanding how it's done, but any guidance that you can give, would be appreciated.

**To Reproduce**
Disable ALL Mods and Resource Packs while running both Forge 43.1.33 and MineCraft 1.19.2, as well as Enchantedtomes 1.19.2-1.9.0-beta

**Expected behavior**
E-Tomes would incorporate an E-Tome containing the enchanted book, resulting in an E-Tome with the book incorporated.

**Screenshots**
![1](https://user-images.githubusercontent.com/115334190/194688478-c7e3e07c-b6c3-48c0-a843-ebde24d46b42.jpg)
![2](https://user-images.githubusercontent.com/115334190/194688479-a263199d-9e2b-4c44-a045-6738cfd1aca9.jpg)

**Additional context**
I have none.

**Comment by EccentricVamp** [comment]
I think you need to remove `minecraft:enchanted_book` from the blacklist.

**Comment by DumbXBoxAcct** [comment]
Thanks for responding, I was hoping that you were right but, unfortunately, it still doesn't work.  Also tried it again, with it whitelisted on the Items list, after I'd removed it from the Excluded Items list and that didn't do it, so I unloaded all the Mods except e-tome, all the Resource Packs & the Shader I was using, with it on the Items list, tried it again & still no dice.  Wondering if maybe the version of Forge that I'm using could be an issue.  Maybe I should try downgrading and seeing if it makes a difference?

**Comment by EccentricVamp** [comment]
If that didn't work, then I'm pretty sure this is an issue on my side. I'll start working on fixing it.

**Comment by DumbXBoxAcct** [comment]
I appreciate it!  Please let me know if I can assist with anything - providing log files, testing, etc.

**Comment by EccentricVamp** [comment]
Sorry for the wait. This should be fixed in Eccentric Tome 1.9.0

Let me know if you're still seeing the issue.

**Comment by DumbXBoxAcct** [comment]
No worries about the wait, I appreciate you staying on it!  Unfortunately, though, it didn't work.  Log files attached, as well as a screenshot.  I took out all my mods except OptiFine and this one to eliminate them as a potential issue.  I'm using ComplementaryReimagined r1.2.2 as my ShaderPack and I'm now on the Forge 43.1.52 client.  

![Crash Screen](https://user-images.githubusercontent.com/115334190/201548450-c3b1482d-6841-4690-bd69-6e78d31c14db.jpg)
[crash-2022-11-13_17.38.02-fml.txt](https://github.com/EccentricVamp/EccentricTome/files/9998373/crash-2022-11-13_17.38.02-fml.txt)
[latest.log](https://github.com/EccentricVamp/EccentricTome/files/9998374/latest.log)

**Comment by EccentricVamp** [comment]
Hmm. I wasn't able to replicate the issue. Tried it on 1.19.2 with Forge 43.1.7 and 43.1.52.

Even stranger is the fact that Eccentric Tome doesn't reference `net.minecraft.entity.Entity` anywhere, so I'm not sure where the error is being thrown from.

I'm continuing to investigate.

**Comment by DumbXBoxAcct** [comment]
Sure makes a whole lot of difference when you load the correct version: I had ver 1.16.5-1.9.0 loaded instead of 1.19.2-1.9.0 for some unknown reason...  With 1.19.2.-1.9.0 loaded, it works perfectly with all of the other mods that I've got loaded, including OptiFine, plus Resource Packs, a Shader, etc. so, nice work!  Thank you for persevering and fixing it, it's really great to see someone like yourself who stands behind their work.

**Comment by EccentricVamp** [comment]
Glad I could help! Closing this issue for now. Feel free to re-open it if the issue comes back up.
