### ISSUE TITLE
Numismatic Overhaul breaks Tome

### ISSUE THREAD

**Issue by Frzncore** [EccentricVamp/EccentricTome#34]
**Versions**
 - Minecraft: [1.19.2]
 - Eccentric Tome: [1.9.1]

**Describe the bug**
Numismatic Overhaul breaks Tome

**To Reproduce**
Install Numismatic Overhaul alongside Tome

**Expected behavior**
Tome is openable but you cannot select a book

**Comment by EccentricVamp** [comment]
Thanks for letting me know. It will probably take me some time to investigate this, but I'll start working on it this weekend.

If I can't fix it in Eccentric Tome, I might need to talk to gliscowo to see if he can fix it in Numisimatic Overhaul.

**Comment by Frzncore** [comment]
Thank you, took me a while to pinpoint, glad to hear that's not in vain

**Comment by EccentricVamp** [comment]
Which version of Numisimatic Overhaul Reforged are you using?

I'm unable to reproduce the issue on 1.0.3. It came out yesterday

**Comment by EccentricVamp** [comment]
I just downgraded to 1.0.2. I was able to replicate the issue on that. Try updating and see if that fixes it

**Comment by Frzncore** [comment]
Yeah it was 1.0.1 and 1.0.2 I was using

**Comment by EccentricVamp** [comment]
No problem. I'm glad it was an easy fix.

Closing this issue for now. Feel free to reopen it if the problem wasn't fixed.
