### ISSUE TITLE
won't work on minecraft 1.18.1 server

### ISSUE THREAD

**Issue by SlightlyOCD** [EccentricVamp/EccentricTome#4]
Minecraft 1.18.1 Forge 39.1.2 
Won't work on a dedicated server with no other mods on it.

[crash-2022-04-03_11.58.01-fml.txt](https://github.com/EccentricVamp/EccentricTome/files/8405293/crash-2022-04-03_11.58.01-fml.txt)

**Comment by EccentricVamp** [comment]
Thanks for the log. That made it easy to fix. I've uploaded v1.0.2 (which fixes this issue). Just waiting for CurseForge to process it.

**Comment by SlightlyOCD** [comment]
Thanks I did not something it won't store all books, but it's already a big
it decreased the amount of books I have to carry thanks.

**Comment by EccentricVamp** [comment]
You're welcome! If you let me know which books they are, I can add them to the mod.
