### ISSUE TITLE
Eccentric Tome duplication with vanilla books

### ISSUE THREAD

**Issue by CelestialAbyss** [EccentricVamp/EccentricTome#40]
**Versions**
 - Minecraft: 1.19.2
 - Eccentric Tome: 1.10.1

**Describe the bug**
When a player puts a regular vanilla book inside the Eccentric Tome then throws the book out, it duplicates the Eccentric Tome along with its inventory on each succeeding throw. I'm aware this may come off as a joke, but I assure you the duplication bug is real and has been reproduced by me and a modpack player by the name of BafflingLion587. *This was with default config settings.*

**To Reproduce**
1. Combine a regular Minecraft book with the Eccentric Tome
2. Sneak and drop the Minecraft books
3. See attached screenshots.

**Expected behavior**
This was *very* unexpected

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://github.com/EccentricVamp/EccentricTome/assets/30322176/c3892d9d-31bc-45e8-b399-a1cf13eff8cc)
![image](https://github.com/EccentricVamp/EccentricTome/assets/30322176/10df320a-8a77-4605-8b40-c00318c163e9)

**Additional context**
Add any other context about the problem
N/A

**Comment by EccentricVamp** [comment]
I was able to replicate the bug.

I think there are 2 issues I'll try to fix
1. Vanilla books shouldn't be able to attach to the Tome with the default config
2. Whole stacks shouldn't get attached to the Tome. Only the first item from the stack should make it into the Tome

Thanks for bringing this to my attention. I'll probably fix it sometime this weekend. I'll update this issue when the fix is published.

**Comment by EccentricVamp** [comment]
This issue should now be fixed in Eccentric Tome 1.10.2. Sorry for the long wait! Let me know if the issue persists.

**Comment by EccentricVamp** [comment]
Version 1.10.2 is now published to CurseForge. Try it out and don't forget to close this issue if it's been resolved.

**Comment by CelestialAbyss** [comment]
Duplication seems to be resolved now, but there is a second issue that my modpack players encountered... I will open a separate issue for that.

Thank you though!
