### ISSUE TITLE
Eccentric Tome should keep its enchantments and custom name after transforming

### ISSUE THREAD

**Issue by gardenappl** [EccentricVamp/EccentricTome#41]
**Is your feature request related to a problem? Please describe.**
I want to use a questing mod to give my players an Eccentric Tome with a Soulbound enchantment, that way they will always have convenient access to documentation. I can enchant individual books with a Soulbound enchant which makes them stay in your inventory after death. The Eccentric Tome itself can be enchanted, too, but it loses its enchant when I transform it into a guide book and then back into a Tome again.

**Describe the solution you'd like**
I would like the Eccentric Tome to retain its enchantments after transforming back and forth. EDIT: custom name given by anvil should be retained as well.

**Describe alternatives you've considered**
* Maybe the enchantment could be retained not just for the Tome, but also automatically applied to all the books inside it? Maybe have a config setting for that? I can see why that would be a problem if other books already have enchantments or interact with enchantments unexpedetly, so maybe that should not be enabled by default.
* Maybe other arbitrary NBT data could be retained besides enchantments.

**Comment by gardenappl** [comment]
> Maybe other arbitrary NBT data could be retained besides enchantments.
I just tested renaming the Tome on an anvil and the custom name does not get retained either.

**Comment by Leclowndu93150** [comment]
Will fix
