### ISSUE TITLE
[1.20.1] No eccentric tome in creative search or in jei

### ISSUE THREAD

**Issue by Thrystan01204** [EccentricVamp/EccentricTome#42]
**Versions**
 - Minecraft: 1.20.1
 - Eccentric Tome: 1.20.1-1.10.1

**Describe the bug**
The search of the book in creative or in JEI doesn't show the item.
It is still craftable, but we can't see the recipe.

**To Reproduce**
Install the mods : https://pastebin.com/4t2NwuXQ

**Expected behavior**
See Eccentric Tome in the inventory search or in JEI

**Screenshots**
![image](https://github.com/EccentricVamp/EccentricTome/assets/47844397/1b14c5f2-c6a1-48aa-916f-0f41cd7efe4b)
![image](https://github.com/EccentricVamp/EccentricTome/assets/47844397/405018ac-30ca-4075-a1ca-47a3d905675b)

**Additional context**
I am making a modpack for my private server

**Comment by taj1994** [comment]
Same issue in All the Mods 9 (currently on ATM 9 v0.2.14 with Eccentric Tome v1.10.1)

**Comment by EccentricVamp** [comment]
I'm looking into this right now. Thanks for bringing it to my attention. Not sure why the basic tome recipe isn't showing up in JEI. I *do* know why it isn't showing up in creative tabs, so I'll try fixing that first.

**Comment by EccentricVamp** [comment]
This issue should now be fixed in Eccentric Tome 1.10.2. Let me know if the issue persists.

**Comment by EccentricVamp** [comment]
Version 1.10.2 is now published to CurseForge. Try it out and don't forget to close this issue if it's been resolved.

**Comment by taj1994** [comment]
I'm not OP, but I'm seeing it in JEI now in ATM 9

**Comment by Thrystan01204** [comment]
Just tried the latest version.
I can see it in JEI (in this case EMI) but not in creative search, otherwise everything seems fine.
![image](https://github.com/EccentricVamp/EccentricTome/assets/47844397/40574a90-4407-4b52-bfd8-dcf6ca686f47)

**Comment by EccentricVamp** [comment]
I did a fresh install of ATM 9. It works in creative search and JEI.

![image](https://github.com/EccentricVamp/EccentricTome/assets/6740013/703583b6-0be3-4824-a94c-159d4fd5fe0b)

@Thrystan01204 are you able to locate the Tome in creative at the bottom of the "Tools & Utilities" tab?

**Comment by Thrystan01204** [comment]
Seems it was on my side, sorry.
I checked and I found it in the tools and utilities tabs and in the search.
Thank you for your speed on this issue.
