### ISSUE TITLE
[Bug] Items that share the same item ID get deleted despite having unique NBT data

### ISSUE THREAD

**Issue by CelestialAbyss** [EccentricVamp/EccentricTome#43]
**Versions**
 - Minecraft: 1.19.2, Forge 43.3.2
 - Eccentric Tome: 1.10.1-1.10.2

**Describe the bug**
This is an issue that modpack players reported... Keeping multiple items with different enchantments and / or have different names but the same item ID only keeps one copy of said item. 

**To Reproduce**
If you store two diamond pickaxes in the same Eccentric Tome but they have different enchantments and / or names, only one of them will be able to be popped out of the tome. The other copies will be deleted from existence as if they never existed.

**Expected behavior**
Keep unique copies of items separate and stored.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Leclowndu93150** [comment]
The eccentric tome is not meant to be an item storage, but instead for guide books.
You can have backpacks for that use case

**Comment by Leclowndu93150** [comment]
fixed in 1.20.1
