### ISSUE TITLE
Essentric Tome duplicating itself within itself?

### ISSUE THREAD

**Issue by GenericQuinn** [EccentricVamp/EccentricTome#44]
**Versions**
 - Minecraft: [1.19.2]
 - Eccentric Tome: [v1.10.2+1.0.1+1.19.2+fabric]
 - Any other relevant mod versions

**Describe the bug**
What the bug is
The eccentric tome appears inside itself, and will multiply whilst changing books
**To Reproduce**
Steps to reproduce the behavior
Right click, select a guide book, left click to clear tome, then the tome itself appears in the options? 
**Expected behavior**
What you expected to happen
Not to see the Eccentric tome within the Eccentric tome
**Screenshots**
If applicable, add screenshots to help explain your problem

![image](https://github.com/EccentricVamp/EccentricTome/assets/76740768/e3a32799-14d8-48e6-8bb8-123fce0be111)
![image](https://github.com/EccentricVamp/EccentricTome/assets/76740768/b1313a9d-45aa-4234-ba40-ff62c3da401d)

**Comment by EccentricVamp** [comment]
Thanks for submitting the issue. This definitely shouldn't be happening. I'll probably have time to look into it sometime next week (or weekend).

I'm a little unclear on what your mod setup is. Eccentric Tome is a Forge mod. But you included Fabric in the version. Are you using Eccentric Tome on fabric?

**Comment by GenericQuinn** [comment]
Ah I do apologise, I just realised I'm using this Fabric port: https://www.curseforge.com/minecraft/mc-mods/eccentric-tome-fabric  
Thanks for bringing this mod back though, I actually have been crying out for Akashic tome to come back for ages! I'll see if I can repost this issue on the ported mod instead of here

**Comment by EccentricVamp** [comment]
Closing for now since this is an issue with another mod. Glad someone finally made a Fabric port. I haven't had the time to do it.
