### ISSUE TITLE
[1.20.1]  Incompatibility crash with Rayon (or Dropz)

### ISSUE THREAD

**Issue by genderneutralnoun** [EccentricVamp/EccentricTome#45]
**Versions**
 - Minecraft: 1.20.1
 - Eccentric Tome: 1.20.1-1.10.2
 - Rayon: 1.7.2+1.20.1
 - Dropz: 2.2.0+1.20.1
 - NeoForge: 47.1.104
 - Prism Launcher: 8.3

**Describe the bug**
The game crashes upon world load with Rayon installed and enabled if Eccentric Tome is also installed and enabled. Disabling Rayon and Dropz lets the world load. However, it appears to be a triple-mod incompatibility, as I have tested enabling only Rayon, Dropz, and Eccentric Tome, which does not crash. I am currently unable to completely debug the issue and thought I would post what I know in case someone more skilled at reading crash logs can help. If I have the chance, I will attempt to debug the issue further and share my findings later.

**To Reproduce**
1. Enable Rayon, Dropz, Eccentric Tome, and possible some other unidentified mod(s).
2. Load the game.
3. Attempt to create or load a world.
4. Game crashes. 

**Expected behavior**
I expected the game to not crash haha.

**Screenshots**
Not applicable.

**Additional context**
I use a lot of performance mods and was in the later stages of testing a modpack. Eccentric Tome is more essential to me than Dropz, so I'll be proceeding without Dropz/Rayon in my modpack testing for now until I have some time to set aside to test things out.
Game/crash log: https://mclo.gs/Eg7DCbu

**Comment by EccentricVamp** [comment]
Crash log is appreciated. I won't be able to properly troubleshoot until the weekend, but I'll read the log now.

It's difficult to tell through all of the layers, but I think the fatal error that causes the actual crash is coming from Rayon. It's a null pointer exception buried on [line 5913](https://mclo.gs/Eg7DCbu#L5913).

The only interaction that I can think of between Rayon/Dropz and Eccentric Tome mod is that they both attempt to change the behavior of dropping the Eccentric Tome item. If you hold <kbd>Shift</kbd> and try to drop the Tome, Dropz tries to "yeet" the book and Eccentric Tome (the mod) tries to eject the currently selected book. I'm not sure if this is causing a null pointer exception, or why it's occurring before any items have even been dropped.

Let me know if you figure out what the third, unidentified mod is. If I'm able to reproduce the bug on my install of Minecraft, then I might be able to write a workaround into Eccentric Tome.

Normally I would recommend you ask the owners of Rayon/Dropz to take a look as well, but it seems like they've archived both projects.

**Comment by genderneutralnoun** [comment]
Oof, really? I might just go back to ItemPhysics then. I liked Rayon's implementation of the physics better than ItemPhysics, but in the long term it's probably better to use a mod that's still supported.

I've been debugging the issue for a bit, but I can't promise I'll end up with any results. I'll let you know if I find anything out.

**Comment by genderneutralnoun** [comment]
Update: The third mod appears to be Advancement Frames, but enabling only it, Rayon, Dropz, Eccentric Tome, and Moonlight Library (required for AF) goes through. It's late, and I'm tired... I don't think I'm gonna be debugging this any more for a while. Thought I'd share what I knew anyway.
