### ISSUE TITLE
Add support for Wizard's Reborn 

### ISSUE THREAD

**Issue by MaxBogomol** [EccentricVamp/EccentricTome#46]
Hi I'm the dev of the Wizard's Reborn mod. 
Due to the non-standard name of the book in my mod, it does not work by default .
Can you add a book to standard items?
Item id - wizards_reborn:arcanemicon

**Comment by EccentricVamp** [comment]
Sure. Should be a simple addition. I'm busy right now but I should be able to get it added sometime this week or weekend.

**Comment by MaxBogomol** [comment]
Looks like it's been a very long week.

**Comment by Leclowndu93150** [comment]
dude 😭😭

Btw why did you leave the NeoForge discord ? I liked your showcases

**Comment by MaxBogomol** [comment]
I left because of the toxic attitude towards me in the showcase chat
