### ISSUE TITLE
Enchanted: Witchcraft book deletion inside Eccentric tome

### ISSUE THREAD

**Issue by Arythames** [EccentricVamp/EccentricTome#47]
**Versions**
 - Minecraft: 1.20.1
 - Eccentric Tome: 1.10.2
 - Enchanted: Witchcraft: 3.0.4

**Describe the bug**
Book deletion/nbt data removed inside the eccentric tome.

**To Reproduce**
Put more than one Enchanted: Witchcraft book into the Eccentric tome
Open any one of the Enchanted: Witchcraft books, then close
Return to the Eccentric tome

**Expected behavior**
After closing any one of the Enchanted books, the other Enchanted books are supposed to still be in the Eccentric tome for use.

**Additional context**
Whichever book you originally opened (from the Enchanted: Witchcraft mod) stays in the Eccentric tome and has no further issues, while the rest of the Enchanted: Witchcraft books get deleted, leaving behind any other book from other mods and the one you opened.

**Comment by EccentricVamp** [comment]
Thanks for finding this. I'm busy this weekend, but I'll try to investigate next weekend
