### ISSUE TITLE
[1.18.2] Improper Switching: Piles?

### ISSUE THREAD

**Issue by HalcyonSeas73** [EccentricVamp/EccentricTome#5]
EccentricTome version: 1.0.1
Patchouli version: 1.18.2-67
Forge version: 40.0.36
Minecraft version: 1.18.2

Patchouli books: Cyclic, Mystical Agriculture, Simple Storage Network
Non-Patchouli: Cooking for Blockheads, RFToolsBase

The Tome combines fine with various books; however, when going to switch with right-click, it seems like they're all piled on top of each other.
![Untitled](https://user-images.githubusercontent.com/84727791/161445282-5a8aceb1-7e7d-45bd-92b3-dec148e3eb47.png)

![Untitled2](https://user-images.githubusercontent.com/84727791/161445578-eca20354-8258-403f-a179-88e13988842d.png)

**Comment by EccentricVamp** [comment]
This should be fixed in v1.0.3, which has now been published
