### ISSUE TITLE
[1.18.2] Disappearing Book

### ISSUE THREAD

**Issue by HalcyonSeas73** [EccentricVamp/EccentricTome#6]
EccentricTome version: 1.0.3
Patchouli version: 1.18.2-67
Forge version: 40.0.36
Minecraft version: 1.18.2

Interestingly, if a mod/its guidebook (such as Botania) is removed, "Air" replaces the book within the Tome. When clicked, the entire Tome is deleted('replaced with air'). 
![Untitled](https://user-images.githubusercontent.com/84727791/161449635-cf6497ec-a41d-4429-82eb-8e0c8e96a78d.png)

When more mods are removed (at least Apotheosis, in this case), the guide book is replaced with as seen below; it can change into that book, which doesnt open, but can be changed back (perhaps the intended behaviour?)

![Untitled2](https://user-images.githubusercontent.com/84727791/161449646-560a8070-4397-4427-94cf-a311f0f8cd59.png)

![Untitled3](https://user-images.githubusercontent.com/84727791/161449685-5098c0f8-8fc6-44c7-bf70-f71c0b699d0e.png)

**Comment by EccentricVamp** [comment]
This will be fixed in version 1.0.4. I haven't released version 1.0.4 yet, since there are some other things that need to be fixed. 

The bug where the Patchouli book persists after uninstalling the mod is not related to Eccentric Tome. You may want to open another issue in the Patchouli repo
