### ISSUE TITLE
Books from the same mod overwrite each other

### ISSUE THREAD

**Issue by skrrt** [EccentricVamp/EccentricTome#7]
**Versions:** MC 1.18.2, ET 1.0.3

**Description:**
If a mod happens to include more than one book such as multiple guides for different aspects of the mod (e.g. Tinkers' Construct), or different variations of some tool book (e.g. Cooking for Blockheads), it is possible to craft an Eccentric Tome already containing one book from said mod with another book from it. However, rather than being appended onto the list of books from that mod, the first book instead gets overwritten by the new one, with no option to keep or recover the old one.

![image](https://user-images.githubusercontent.com/5098830/161558658-3af90da1-8eb4-4a97-8ce5-fa2dc4ed837e.png)
![image](https://user-images.githubusercontent.com/5098830/161558686-8fd6736e-2d70-447b-bc45-214270d6a1a7.png)

**Comment by HalcyonSeas73** [comment]
Agreed, I've noticed this as well. Perhaps it's in how the books are registered...? I believe this also occurs with both books from Botania.

**Comment by EccentricVamp** [comment]
I'd intended to gracefully reject books that have already been added to the Tome (instead of just swallowing them). So, I'll leave this open as a bug.

Allowing multiple books is definitely a useful feature, but not a bug, so I'll open a separate issue for that.

**Comment by EccentricVamp** [comment]
This will be implemented in version 1.0.4, which I should be releasing soon.
