### ISSUE TITLE
Support multiple books from the same mod

### ISSUE THREAD

**Issue by EccentricVamp** [EccentricVamp/EccentricTome#8]
Originally requested in #7 by @skrrt

Examples of mods with multiple books include
* Cooking for Blockheads
* Botania
* Tinker's Construct

I'm not sure how the UI for this should work, so discussion would be appreciated.

**Comment by skrrt** [comment]
> I'm not sure how the UI for this should work, so discussion would be appreciated.
Considering that the tome already has all the names of the books under a heading associated with their respective mods, I can't imagine the UI would have to be changed too drastically - any other books belonging to a mod could simply be listed alongside the first one of a mod in the tooltip, and the book selection screen may as well remain the same.

I know that the approach taken by Akashic Tome would have once been to have another compound tag for each new book named "modid#" (e.g. "cookingforblockheads1" for a second CFB book). As far as the NBT data is concerned, either this same approach could be used for Eccentric Tome, or, if that's not clean enough, each mod ID compound could have a nested compound (0, 1, 2 ...) containing an individual book.

**Comment by EccentricVamp** [comment]
That makes sense for the tooltip and serialization. I was more unsure about how users expect to retrieve different books from the same mod. I want the keep the `Shift` + `Right Click` behavior as simple as possible, so this would probably have to be done through the `Right Click` book selection screen.

Maybe organize the books into rows in the selection screen, where each row corresponds to a given mod? That's what I would expect as a user, but I'm also weird.

**Comment by EccentricVamp** [comment]
I decided to go with your suggestion of just keeping the existing UI. This will be implemented in version 1.0.4, which I should be releasing soon.

 Might revisit this in the future, but I tested it and it works well enough for now.

**Comment by EccentricVamp** [comment]
1.0.4 has now been published to CurseForge for 1.18.2. I've labeled it as an alpha since there were some big changes in the backend. So, backup your saves and be on the lookout for bugs.

If there aren't any issues after a few days, I'll republish Eccentric Tome 1.0.4 for Minecraft 1.18.2 and 1.18.1 as a normal release.
